### ISSUE TITLE
Allow BAF trucks to carry supply crates

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#10]
Update kp_liberation_comfig.sqf section
/* - Configraiton settings for crates transported by vehicles.
to include BAF transport vehicles (large and small covered and uncovered trucks)

**Comment by nihilogist** [comment]
Probably gonna leave this one for a while, as it involves figuring out a bunch of co-ordinates of where the boxes should magically glue to trucks ;)

**Comment by DoctorTemporis** [comment]
I think I have the loadbed co-ordinates somewhere, will look into it,

**Comment by DoctorTemporis** [comment]
The crates are attached to trucks by the client side function [do_load_box.sqf](https://github.com/nihilogist/tactical-liberation-tanoa/blob/master/scripts/client/ammoboxes/do_load_box.sqf). This function pulls the offsets for crate attachment from [kp_liberation_config.sqf](https://github.com/nihilogist/tactical-liberation-tanoa/blob/master/kp_liberation_config.sqf). It uses the [attachTo ](https://community.bistudio.com/wiki/attachTo)command to do this (which can cause some odd physics effects if both items are physics enabled, but whatever). This command is syntaxed **object1 attachTo [object2, offset, memPoint]** and the code doesn't use memPoint. It just pulls the offset values from the appropriate entry for the vehicle you are loading into from the config file and applies it.

However, attachTo applies the offset value from the object1 center to the object2 center if no memPoint is provided. You'll notice that there is only 1 set of offsets per vehicle. There are three types of crates (the specific crates to be used can be defined in config, actually), all of which are of different sizes (same XY footprint, but different _heights_).

What this means is that when you set the offset based on the biggest crate (the ammo one is tallest), when you attach a fuel crate it hovers above the cargo bed, and when you attach a supply crate, it hovers higher still. If you do it the other way, setting it based on the smallest crate, then the crates clip into the vehicle. KP have 'solved' this problem by only applying cargo carrying to vehicles with sides, so you can't see the hovering.

**Comment by DoctorTemporis** [comment]
However, the BAF cargo vehicles do /not/ have sides, which would mean we'd see antigravity crates. Will now test to see if the vehicles explode if I set it based on the smallest crate and let it clip through.

**Comment by DoctorTemporis** [comment]
It's not clear to me right now how this works for the crates in the storage bays (berms), because they _don't_ do this. They are all placed at the same heights.

**Comment by DoctorTemporis** [comment]
Ah. The crates go into storage via the function [F_kp_crate_to_storage.sqf](https://github.com/nihilogist/tactical-liberation-tanoa/blob/master/scripts/shared/functions/F_kp_crate_to_storage.sqf) and that _does_ adjust for the heights of the different boxes.

**Comment by DoctorTemporis** [comment]
Closed with 8fb2c34576cdcdd633374a46d9e0ff2fc9e15873 although adding a mechanic to resolve the other crate height will be a Milestone 2 bug. For now, the MX58 can carry up to 8 crates, although the ones that are not ammo will hover slightly.
