### ISSUE TITLE
Sector Activation Range

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#13]
Rebalance activation range (GRLIB_sector_size in kp_liberation_config.sqf) to 1500 from 1100m given shortness of activation producing odd effects in Liberation_Altis

**Comment by DoctorTemporis** [comment]
It was prior increased from 1000 to 1100 m in earlier commit, I think that we need to go to 1500.

**Comment by nihilogist** [comment]
I did actually start with it at 1500m, but looking at the map we could end up with some odd effects in the other direction, where we just continually activate sectors. We can bump it up a bit, but we'll need to watch out for that.

**Comment by DoctorTemporis** [comment]
Discussed - leave @ 1100 for now & check
