### ISSUE TITLE
FOB Construction Range Increase

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#14]
Increase GRLIB_fob_range in kp_liberation_config.sqf from 125m to 200m to allow for construction of FOBs with larger acess areas to avoid AI confusion when navigating, and for placement of static defenses / defensive patrols.

**Comment by nihilogist** [comment]
Fixed with commit 7a491882f8f8d740919ac10666db0f80f0adcc9d
