### ISSUE TITLE
Finalise BLUFOR vehicle list

### ISSUE THREAD

**Issue by nihilogist** [nihilogist/tactical-liberation-tanoa#2]
Need to run through the BLUFOR vehicles that are available and decide if there are any more that we want to add.

Mod requests can also be added here.

**Comment by DoctorTemporis** [comment]
Need to replace trucks and convoy trucks with BAF trucks not generic heavy carriers.
Need to replace support_vehicles with BAF support vehicles for repair/fuel/ammo
Can remove 6seat wildcats (just have 8 seat wildcats) but we need to ensure all 4 types of 8 seat wildcat are included (transport, CAS-AT, CAS-PG, hellfire)
Need to add BAF rigid raiders (boats) to light vehicles list and remove B_Boat_Armed_01_minigun_F

**Comment by DoctorTemporis** [comment]
Review aircraft:
Remove all firewill aircraft mods (F35B, F15, Harrier). Replace with Firewill A10C.
Add ospreys (blackfish), armed variant and vehicle carrier variant.

**Comment by nihilogist** [comment]
Boats: have removed the NATO minigun boat and added BAF rigid raiders.

**Comment by nihilogist** [comment]
Helis: have removed 6 seat Wildcat. Have added all seven 8 seat Wildcat variants.

**Comment by nihilogist** [comment]
Current BLUFOR fixed wing options are the A10 from RHS (given that we already have it) and the Firewill Harrier.
@DoctorTemporis :
- are you sure you want to drop the Harrier? 
- Is there a reason to get the Firewill A10 over the RHS one?

**Comment by DoctorTemporis** [comment]
@nihilogist I'm trying to lower the number of extra flight aircraft mods, although it would be tempting to retain the harrier even if we drop the Strike Eagle.
There is a reason to use the Firewill A10C (avionics & rearming function)

**Comment by nihilogist** [comment]
Added repair and fuel trucks to the blufor build list and repair / refuel sources list.

**Comment by DoctorTemporis** [comment]
Closed with commit 1611357bd3d3c9d0b6b56b6c5edbb50be0ac7da3

**Comment by DoctorTemporis** [comment]
Closed with commit 1611357bd3d3c9d0b6b56b6c5edbb50be0ac7da3
