### ISSUE TITLE
Ammunition Types

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#21]
We have not restricted ammunition types in the arsenal.

This has made a lot of magazine types from RHSUSAF available for 5.56 weapons. Since we have a smaller number of allowed weapons, we may want to actually review & whitelist ammo types to prevent choice paralysis.

**Comment by nihilogist** [comment]
That'd be good, though I'm not sure how that works - there seemed to be an array of magazines in the config file but it was empty when I found it, so not sure what the effect there would be. If we can figure out how to limit / specify magazine selection that would be *great*.

**Comment by DoctorTemporis** [comment]
I have tried it - if you add a magazine to the array, all other magazines are then forbidden from the arsenal unless also present in the global whitelist. If the array is blank then all are allowed.  I _can_ work out for each of our weapons what allowed magazines should be, but it may take awhile because I also have to account for (and include) virtual magazines (eg for the NLAW) which will otherwise cause pantsmode if not available to the user if they select the launcher in the launcher slot, etc.

**Comment by nihilogist** [comment]
... that sounds like it's the _correct_ solution, even if it is a bunch more work. Possibly the way to approach it is to run through it iteratively, testing and fixing for chunks of the available weapons / ammo types as we go.

**Comment by nihilogist** [comment]
Added first set of ammunition configs.

Still need:
- sidearms
- BAF launchers?
- AMR

**Comment by DoctorTemporis** [comment]
Tested this. Works, although as a result of introducing whitelist we need to also whitelist:

Sidearm ammunition (as noted above)
Launcher magazines (as noted above) 
Deal with the LRPAS(AMR) problem (as noted above)
but also now:
Grenades (both thrown and launched - all now 'gone' until whitelisted)
Explosives (placed, thrown, incendiaries, etc - all now 'gone' until whitelisted)
Mortar rounds (for the 60mm man portable)

**Comment by DoctorTemporis** [comment]
SHOTGUN TO BE ADDED TO WEAPONS - UK3CB_BAF_L128A1

//SOFLAM Batteries
Laserbatteries

//AMR Magazines
UK3CB_BAF_127_10Rnd
UK3CB_BAF_127_10Rnd_AP

//Shotgun Magazines
UK3CB_BAF_12G_Pellets
UK3CB_BAF_12G_Slugs

//Sidearm Magazines
UK3CB_BAF_9_17Rnd

//Virtual Launcher Magazines
uk3cb_baf_nlaw_mag
rhs_fim92_mag

//UGL Rounds
UK3CB_BAF_1Rnd_HE_Grenade_Shell
UK3CB_BAF_1Rnd_HEDP_Grenade_Shell
UK3CB_BAF_UGL_FlareCIR_F
UK3CB_BAF_UGL_FlareWhite_F
UK3CB_BAF_1Rnd_Smoke_Grenade_shell
UK3CB_BAF_1Rnd_SmokeBlue_Grenade_shell
UK3CB_BAF_1Rnd_SmokeGreen_Grenade_shell
UK3CB_BAF_1Rnd_SmokeRed_Grenade_shell

//Grenades
B_IR_Grenade
UK3CB_BAF_SmokeShell
UK3CB_BAF_SmokeShellBlue
UK3CB_BAF_SmokeShellGreen
UK3CB_BAF_SmokeShellRed
ACE_HandFlare_White
ACE_HandFlare_Green
ACE_HandFlare_Red
rhs_mag_m67
rhs_mag_mk84

//Explosives
DemoCharge_Remote_Mag
SatchelCharge_Remote_Mag

**Comment by nihilogist** [comment]
Fixed with commit 6de7f1f52257cfd0d30e5be96ada71464a21d09c

Awaiting testing.

**Comment by DoctorTemporis** [comment]
Tested and confirmed OK - although note RE LRPAS workaround in issue #22
