### ISSUE TITLE
LRPAS Ammo Not Showing in Arsenal

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#22]
Some sort of issue with the LRPAS.

It takes either
UK3CB_BAF_127_10Rnd 
or
UK3CB_BAF_127_10Rnd_AP
magazines.

However, even when choosing the filter in the arsenal for ammo for primary weapon, or when choosing show all ammo, these magazines do not display, making the weapon unusable.

This occurs even if the magazine has been added to the arsenal whitelist (tested, which removed all other ammo types, but still did not show the added ones).

**Comment by nihilogist** [comment]
Which weapon is the LRPAS?

**Comment by DoctorTemporis** [comment]
It's the anti-materiel rifle. Very popular for dealing with TIGRs - or in this future case, GMG HMMWVs.

**Comment by nihilogist** [comment]
Bah. So kind of an important one. Fudge.

Can you pull the ammo for this out of a logistics pack? That might be a temporary solution while we try to figure out whatt the heck is going on.

**Comment by nihilogist** [comment]
Think this is a bug in the mod itself.

Place a unit in the EDEN editor.

Edit the unit's inventory with the ACE arsenal - add the LRPAS. Try to select ammunition for it - none is available.

Edit the unit's inventory with the BI arsenal - add the LRPAS. Select ammunition for it - it is available.

**Comment by DoctorTemporis** [comment]
Replicated. Even if on the magazine whitelist, the LRPAS ammo types don't show. However, if you fire 1 shot with the weapon, you can then add the non-AP type (the default weapon load) in the arsenal (it suddenly appears).

Resolution: either build the loadout in a virtual arsenal separate from the liberation whitelist and then load it (because the whitelist will allow the ammo types through and they will then appear in the arsenal), or fire a shot and then finalise the loadout.
