### ISSUE TITLE
Mission Parameters

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#26]
We need to codify the parameter settings to be used in running the mission. Critical parameters and available options are noted in table below.

Critical Parameter | Setting 1 | Setting 2 | Setting 3 | Setting 4 | Setting 5 | Setting 6 | Setting 7 | Setting 8 | Setting 9 | Setting 10 | Setting 11 | Setting 12 | Setting 13
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Maximum Amount of AI Units | 50%  - Local Hosting | 75% - Dedicated Server | 100% - Dedicated Server | 125% - Dedicated Server with 1 Headless Client | 150% - Dedicated Server with 2 Headless Clients | 200% - Dedicated Server with at least 2 Headless Clients |   |   |   |   |   |   |  
Difficulty | Tourist | Easy | Normal | Moderate | hard | Extreme | Ludicrous | Oh god oh god we're all gonna die |   |   |   |   |  
OPFOR Aggressivity | Anemic | Weak | Normal | Strong | Extreme |   |   |   |   |   |   |   |  
Hostile Presence Adapts to Player Count | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Civilian Activity | None | Reduced | Normal | Increased |   |   |   |   |   |   |   |   |  
Start Campaign with FOB Already Built | No | Yes |   |   |   |   |   |   |   |   |   |   |  
Start FOB Provided as | FOB Container | FOB Truck |   |   |   |   |   |   |   |   |   |   |  
Max # of FOBs | 3 | 5 | 7 | 10 | 15 | 20 | 26 |   |   |   |   |   |  
AI Recruitment Limit Per Squad | 0 | 1 | 2 | 4 | 6 | 8 | 10 | 12 | 16 | 20 | 24 | 30 | 36
BLUFOR Defenders in Own Sectors | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Auto-danger Behaviour on BLUFOR forces | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Day Duration (hours) | 3 | 4 | 6 | 8 | 12 | 24 |   |   |   |   |   |   |  
Shorter Nights | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Weather | Always Sunny | Random without Rain | Random |   |   |   |   |   |   |   |   |   |  
Dynamic for (A3 Vanilla) | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Resources Multiplier | x0.25 | x0.5 | x0.75 | x1 | x1.25 | x1.5 | x2 | x3 |   |   |   |   |  
Arsenal | BI Arsenal | ACE Arsenal |   |   |   |   |   |   |   |   |   |   |  
Victory Condition | All Capitals | All Capitals and Military Bases | All Capitals and 60% of Sectors | All Capitals and 80% of Sectors | All Sectors |   |   |   |   |   |   |   |  
Mobile Respawn | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Mobile Respawn Cooldown | Disabled | 5 | 10 | 15 | 20 | 30 | 60 |   |   |   |   |   |  
Mobile Arsenal | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Teamkill Penalty | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Civil Rep Penalty for buildings | Damaged | Full Destroyed | HACKZORED |   |   |   |   |   |   |   |   |   |  
HALO Jump | Disabled | 0min | 5min | 10min | 15min | 20min | 30min |   |   |   |   |   |  
Clear Spawned Vehicle Cargo | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Chance that Enemies will stay in Damaged   Vehicle | 0 | 25 | 50 | 75 | 100 |   |   |   |   |   |   |   |  
Max Sector Deactivation Delay (increases   after 5th Activated Minute) | Disabled | 5 | 10 | 15 | 20 | 25 | 30 |   |   |   |   |   |  
Commander Limited Zeus Interface | Enabled | Disabled |   |   |   |   |   |   |   |   |   |   |  
Cleanup Abandoned Vehicles Outside FOB | Disabled | Enabled - 1h Delay | Enabled - 2h Delay | Enabled - 4h Delay |   |   |   |   |   |   |   |   |

**Comment by DoctorTemporis** [comment]
These are my suggested selections - @nihilogist to review and set.

Critical Parameter | Selection for TACD-Tanoa
-- | --
Maximum Amount of AI Units | 125% - Dedicated Server with 1 Headless Client
Difficulty | Normal
OPFOR Aggressivity | Strong
Hostile Presence Adapts to Player Count | Enabled
Civilian Activity | Normal
Start Campaign with FOB Already Built | No
Start FOB Provided as | FOB Container
Max # of FOBs | 10
AI Recruitment Limit Per Squad | 12
BLUFOR Defenders in Own Sectors | Enabled
Auto-danger Behaviour on BLUFOR forces | Enabled
Day Duration (hours) | 6
Shorter Nights | Enabled
Weather | Random
Dynamic for (A3 Vanilla) | Enabled
Resources Multiplier | x1
Arsenal | ACE Arsenal
Victory Condition | HACKZORED
Mobile Respawn | Enabled
Mobile Respawn Cooldown | 5
Mobile Arsenal | Disabled
Teamkill Penalty | Disabled
Civil Rep Penalty for buildings | HACKZORED
HALO Jump | Disabled
Clear Spawned Vehicle Cargo | Enabled
Chance that Enemies will stay in Damaged Vehicle | 75
Max Sector Deactivation Delay (increases after 5th   Activated Minute) | 5
Commander Limited Zeus Interface | Enabled
Cleanup Abandoned Vehicles Outside FOB | Enabled - 4h Delay

**Comment by nihilogist** [comment]
I'd be tempted to drop the max AI squad size to 10, mainly because as soon as you get past 10 squad members the control of them becomes an absolute arse. Other than that, I think that's cool.

**Comment by nihilogist** [comment]
Fixed with commit c38ed3f755969fa1cc75cdf813a0e53625fc1883
