### ISSUE TITLE
ACE Medical Bleed Out Timer

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#27]
Find out where this is set (because the mission params say the value in there is not used if you play with ACE medical) and double it.

**Comment by nihilogist** [comment]
It's set in the EDEN Editor. I've already altered it a bit to - IIRC - 3 minutes. Can be found under one of the menus about Attributes - it's called Configure Add-ons?

**Comment by DoctorTemporis** [comment]
Resolved with commit 130787f3e3d2e73f238489b00509f4de64ed2488
