### ISSUE TITLE
ACE Ballistics Scope Implementation

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#32]
Settings for ACE Ballistics in the mission are being overridden by the settings on the server.

**Comment by DoctorTemporis** [comment]
The relevant options are under the ACE Scopes submenu and are:
1. Enable ACE Scope Adjustment
2. Force Adjustment Turrets

**Comment by nihilogist** [comment]
Not quite sure what's needed here: these settings are forced in the mission file - do you want them removed back to vanilla?

**Comment by DoctorTemporis** [comment]
The settings forced in the mission file are not being respected by the server (option says 'server overrides this value'

**Comment by DoctorTemporis** [comment]
Do we need to do something about server.cfg? Let's test latest commits and review.
