### ISSUE TITLE
ACE Map Zoom Limitation

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#33]
The ACE Mapzoom restriction is stopping grid referencing on maps lower than 2 digit. This isn't practical for indirect fire use, so we should turn this back off again and have it as it was in Altis.

**Comment by DoctorTemporis** [comment]
Setting to be disabled is ACE Maps - Limit Map Zoom

**Comment by nihilogist** [comment]
Fixed with commit dd6f4aa019e38e2c1fb5b32ab330602c003932dd
