### ISSUE TITLE
Blufor Vehicle / Vehicle Group Spawns in Georgetown area every 20-30 minutes

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#38]
We have been having a lot of trouble with random activations in the Georgetown area. First we thought it was a yeeted boat, then crates. Restarting the server 'fixed' it, sometimes immediately, sometimes not for awhile. 

So over the last 2 operations I did some testing with full Zeus enabled and every time the "Georgetown Area" went mad, used the zeus power "add all blue side units on map to zeus" to get a listing of all of the blufor units.

And what did I see? A "BLUFOR" Busk I Bradley with AI crew. Trundling around Georgetown. Not, as far as I could tell, shooting anything, or getting shot at, but making the sectors all around activate.

I deleted it using Zeus, and the sectors calmed down in 5 mins as they should. Then, roughly 20-30 mins later, they all went mad again. This time, a Blufor Rooikat, doing the same thing. Deleted. And again after a certain amount of elapsed time - this time two bradleys!

I assume that this is something going wrong with the "Patrol" spawning system.

**Comment by nihilogist** [comment]
Believe fixed with commit 3c7cb1162487bfc639c82313836aa660789183bd
