### ISSUE TITLE
Balance OPFOR vehicle selections

### ISSUE THREAD

**Issue by nihilogist** [nihilogist/tactical-liberation-tanoa#5]
Once we've set the vehicles that are available to the OPFOR side, we need to balance the probablility of selecting certain vehicles by adjusting the lists.

Opinions on balance welcome here.

**Comment by nihilogist** [comment]
Testing on this indicated that the GMG-equipped trucks were super lethal and very happy to go full-auto with grenades. Possibly we should restrict their spawn rates a bit.

**Comment by DoctorTemporis** [comment]
Pre-adjustment apex.sqf
[apex.zip](https://github.com/nihilogist/tactical-liberation-tanoa/files/3876996/apex.zip)

**Comment by DoctorTemporis** [comment]
Rebalanced prior to general overhaul with commit c5b190c0e99f06b4d3b4c92f3c1a6b702b04bf07
