### ISSUE TITLE
Find suitable BLUFOR MANPAD

### ISSUE THREAD

**Issue by nihilogist** [nihilogist/tactical-liberation-tanoa#8]
The BLUFOR troops are probably going to need some kind of AA solution at some point. Might need to find a suitable mod and introduce it.

**Comment by nihilogist** [comment]
Without adding further mods, we do have the option of the Stinger used by the US forces. Not sure on the in-game implementation of it tho.

**Comment by DoctorTemporis** [comment]
Have reviewed stinger (rhs_weap_fim92) and approve as BLUFOR manpad for inclusion.

**Comment by nihilogist** [comment]
Fixed with commit a02bf411d3a44097f3fdc79c302293ac95ce1f80
