### ISSUE TITLE
Rebalance Civilian Kill / Building Damage Penalties

### ISSUE THREAD

**Issue by DoctorTemporis** [nihilogist/tactical-liberation-tanoa#9]
Rebalance and update values in kp_liberation_config.sqf for 
KP_liberation_cr_kill_penalty
KP_liberation_cr_building_penalty
KP_liberation_cr_resistance_penalty
KP_liberation_cr_sector_gain
KP_liberation_cr_wounded_chance
KP_liberation_cr_wounded_gain

**Comment by nihilogist** [comment]
Fixed with commit f5058f30521d0b9b6b7e5a5b5b81b83437994989

There's now a flat penalty for destroying buildings in a sector: if *any* buildings are destroyed then the penalty applies.
